# Generated by Django 6.0.6 on 2026-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('content', models.TextField(verbose_name='Текст записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запись в гостевую книгу',
                'verbose_name_plural': 'Записи в гостевую книгу',
                'db_table': 'guestbook_entry',
            },
        ),
    ]
